from tap_hubspot import RowTransformer
from singer import UNIX_MILLISECONDS_INTEGER_DATETIME_PARSING

class TestRelationalDBFieldType(unittest.TestCase):
    def test_process_na(self):
        row = {'addedAt': 1549520648318, 
                'vid': 151, 
                'canonical-vid': 151, 
                'merged-vids': [], 
                'portal-id': 'N/A', 
                'is-contact': True, 
                'profile-token': 'test_token', 
                'profile-url': 'https://app.hubspot.com/contacts/5389540/contact/151', 
                'properties': {'firstname': {'value': 'Firstname'}, 
                'lastmodifieddate': {'value': '1549521003396'}, 
                'lastname': {'value': 'Lastname'}}, 
                'form-submissions': [], 'list-memberships': [], 
                'identity-profiles': [{'vid': 151, 
                                        'saved-at-timestamp': 1549520648194, 
                                        'deleted-changed-timestamp': 0, 
                                        'identities': [{'type': 'EMAIL', 
                                        'value': 'user@email.com', 
                                        'timestamp': 1549520648175, 
                                        'is-primary': True}, 
                                    {'type': 'LEAD_GUID', 
                                    'value': '76f4s5sq-5308-4796-96c4-4b7381e17cg3', 
                                    'timestamp': 1549520648191}]}], 
                                    'merge-audits': [], 
                                    'version': 7,
                                    'versionTimestamp': 1549521003697}
        transformer = RowTransformer(UNIX_MILLISECONDS_INTEGER_DATETIME_PARSING)
        processed_row = transformer.replace_na_with_none(row)

        self.asserEqual(processed_row, 
                {'addedAt': 1549520648318, 
                'vid': 151, 
                'canonical-vid': 151, 
                'merged-vids': [], 
                'portal-id': None, 
                'is-contact': True, 
                'profile-token': 'test_token', 
                'profile-url': 'https://app.hubspot.com/contacts/5389540/contact/151', 
                'properties': {'firstname': {'value': 'Firstname'}, 
                'lastmodifieddate': {'value': '1549521003396'}, 
                'lastname': {'value': 'Lastname'}}, 
                'form-submissions': [], 'list-memberships': [], 
                'identity-profiles': [{'vid': 151, 
                                        'saved-at-timestamp': 1549520648194, 
                                        'deleted-changed-timestamp': 0, 
                                        'identities': [{'type': 'EMAIL', 
                                        'value': 'user@email.com', 
                                        'timestamp': 1549520648175, 
                                        'is-primary': True}, 
                                    {'type': 'LEAD_GUID', 
                                    'value': '76f4s5sq-5308-4796-96c4-4b7381e17cg3', 
                                    'timestamp': 1549520648191}]}], 
                                    'merge-audits': [], 
                                    'version': 7,
                                    'versionTimestamp': 1549521003697})
